development: &default
  adapter: postgresql
  #adapter: jdbcpostgresql
  encoding: unicode
  database: pg_power_dummy_development
  pool: 5
  username: postgres
  password: secret
  host: localhost

test:
  <<: *default
  database: pg_power_dummy_development
