development: &default
  adapter: postgresql
  #adapter: jdbcpostgresql
  encoding: unicode
  database: pg_power_dummy_development
  pool: 5
  username: pg_power
  password: pg_power
  host: localhost

test:
  <<: *default
  database: pg_power_dummy_test
