development:
  adapter: postgresql
  encoding: unicode
  database: pg_power_dummy_development
  pool: 5
  username: postgres
  password: secret
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pg_power_dummy_test
  pool: 5
  username: postgres
  password: secret
  host: localhost
